<?php
define('_DB_SERVER_', 'localhost');
define('_DB_NAME_', 'prestashop');
define('_DB_USER_', 'root');
define('_DB_PASSWD_', '');
define('_DB_PREFIX_', 'ps_');
define('_MYSQL_ENGINE_', 'InnoDB');
define('_PS_CACHING_SYSTEM_', 'CacheMemcache');
define('_PS_CACHE_ENABLED_', '0');
define('_MEDIA_SERVER_1_', '');
define('_MEDIA_SERVER_2_', '');
define('_MEDIA_SERVER_3_', '');
define('_COOKIE_KEY_', 'T78Us55Evn8CSqFDBJ7KGWPBknpz7RfSpmsXYC9FeG2GojrbIR7Pk4JU');
define('_COOKIE_IV_', 'zpdknhAZ');
define('_PS_CREATION_DATE_', '2014-12-03');
if (!defined('_PS_VERSION_'))
	define('_PS_VERSION_', '1.6.0.9');
define('_RIJNDAEL_KEY_', 'Q6J4EJQjc2eWt718kjz4YcLAWW5y8V15');
define('_RIJNDAEL_IV_', 'gt25i8K+2fJNH8buiAeqRQ==');
